
commands: ['forward',
           'backward',
           'turn left',
           'turn right',
           'stop',
           'look left',
           'look right',
           'happy',
           'angry',
           'sad',
           'neutral',
           'confused']